# Generated by Django 5.2.3 on 2025-06-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="telegram_id",
            new_name="chat_id",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_name",
        ),
    ]
