# Generated by Django 5.2.3 on 2025-06-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_telegram_id_telegramuser_chat_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
